"""
In-memory store for real infrastructure data ingested from agents.
Also holds simulated infra snapshots generated by the engine.
"""
from datetime import datetime, timezone
from typing import Optional

# host -> list of snapshots (ring buffer, last 100)
_infra_snapshots: dict[str, list[dict]] = {}

# host -> list of Windows Event Log entries (last 200)
_win_events: dict[str, list[dict]] = {}

# host -> list of IIS log aggregations (last 100)
_iis_aggregations: dict[str, list[dict]] = {}

# All raw IIS entries (last 500 globally)
_iis_raw: list[dict] = []


def push_infra_snapshot(host: str, snapshot: dict):
    if host not in _infra_snapshots:
        _infra_snapshots[host] = []
    _infra_snapshots[host].append(snapshot)
    if len(_infra_snapshots[host]) > 100:
        _infra_snapshots[host].pop(0)


def push_win_event(host: str, event: dict):
    if host not in _win_events:
        _win_events[host] = []
    _win_events[host].append(event)
    if len(_win_events[host]) > 200:
        _win_events[host].pop(0)


def push_iis_aggregation(host: str, agg: dict):
    if host not in _iis_aggregations:
        _iis_aggregations[host] = []
    _iis_aggregations[host].append(agg)
    if len(_iis_aggregations[host]) > 100:
        _iis_aggregations[host].pop(0)


def push_iis_raw(entries: list[dict]):
    _iis_raw.extend(entries)
    if len(_iis_raw) > 500:
        del _iis_raw[:len(_iis_raw) - 500]


def get_latest_snapshot(host: str) -> Optional[dict]:
    snaps = _infra_snapshots.get(host, [])
    return snaps[-1] if snaps else None


def get_snapshots(host: str, limit: int = 60) -> list[dict]:
    return _infra_snapshots.get(host, [])[-limit:]


def get_all_latest() -> dict[str, dict]:
    return {
        host: snaps[-1]
        for host, snaps in _infra_snapshots.items()
        if snaps
    }


def get_win_events(host: Optional[str] = None, limit: int = 50) -> list[dict]:
    if host:
        return _win_events.get(host, [])[-limit:]
    all_events = []
    for evts in _win_events.values():
        all_events.extend(evts)
    return sorted(all_events, key=lambda e: e.get("timestamp", ""), reverse=True)[:limit]


def get_iis_raw(host: Optional[str] = None, limit: int = 100) -> list[dict]:
    if host:
        return [e for e in _iis_raw if e.get("host") == host][-limit:]
    return _iis_raw[-limit:]


def get_known_hosts() -> list[str]:
    return list(_infra_snapshots.keys())


def reset_infra():
    _infra_snapshots.clear()
    _win_events.clear()
    _iis_aggregations.clear()
    _iis_raw.clear()
